backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "home"
    files:
      - file: "src/pages/home/home.md"
        label: "home file label"
        name: "home file name"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default fields"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
